#!/bin/sh
usage() {
	echo "usage: bump-version <version-id>"
}

if [ $# -ne 1 ]; then
	usage
	exit 1
fi

if ! sed 's/^GITFLOW_202_VERSION=.*$/GITFLOW_202_VERSION='$1'/g' git-flow-version-202 > .git-flow-version-202.new; then
	echo "Could not replace GITFLOW_202_VERSION variable." >&2
	exit 2
fi

mv .git-flow-version-202.new git-flow-version-202
git add git-flow-version-202
git commit -m "Bumped version number to $1" git-flow-version-202
